#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - build-essential
  - pypy3
runcmd:
  - 'wget -qO - "https://raw.githubusercontent.com/openXC7/toolchain-installer/main/toolchain-installer.sh" | bash'
